/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SearchRouteImport } from './routes/search'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminQueueRouteImport } from './routes/admin.queue'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as OperatorDashboardRouteImport } from './routes/operator.dashboard'
import { Route as OperatorProcessingRouteImport } from './routes/operator.processing'
import { Route as OperatorResultRouteImport } from './routes/operator.result'
import { Route as OperatorUploadRouteImport } from './routes/operator.upload'
import { Route as OperatorUploadsRouteImport } from './routes/operator.uploads'
import { Route as VerifierDashboardRouteImport } from './routes/verifier.dashboard'
import { Route as VerifierQueueRouteImport } from './routes/verifier.queue'
import { Route as VerifierReviewRouteImport } from './routes/verifier.review'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminQueueRoute = AdminQueueRouteImport.update({
  id: '/admin/queue',
  path: '/admin/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorDashboardRoute = OperatorDashboardRouteImport.update({
  id: '/operator/dashboard',
  path: '/operator/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorProcessingRoute = OperatorProcessingRouteImport.update({
  id: '/operator/processing',
  path: '/operator/processing',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorResultRoute = OperatorResultRouteImport.update({
  id: '/operator/result',
  path: '/operator/result',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorUploadRoute = OperatorUploadRouteImport.update({
  id: '/operator/upload',
  path: '/operator/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorUploadsRoute = OperatorUploadsRouteImport.update({
  id: '/operator/uploads',
  path: '/operator/uploads',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifierDashboardRoute = VerifierDashboardRouteImport.update({
  id: '/verifier/dashboard',
  path: '/verifier/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifierQueueRoute = VerifierQueueRouteImport.update({
  id: '/verifier/queue',
  path: '/verifier/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifierReviewRoute = VerifierReviewRouteImport.update({
  id: '/verifier/review',
  path: '/verifier/review',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/queue': typeof AdminQueueRoute
  '/admin/users': typeof AdminUsersRoute
  '/operator/dashboard': typeof OperatorDashboardRoute
  '/operator/processing': typeof OperatorProcessingRoute
  '/operator/result': typeof OperatorResultRoute
  '/operator/upload': typeof OperatorUploadRoute
  '/operator/uploads': typeof OperatorUploadsRoute
  '/verifier/dashboard': typeof VerifierDashboardRoute
  '/verifier/queue': typeof VerifierQueueRoute
  '/verifier/review': typeof VerifierReviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/queue': typeof AdminQueueRoute
  '/admin/users': typeof AdminUsersRoute
  '/operator/dashboard': typeof OperatorDashboardRoute
  '/operator/processing': typeof OperatorProcessingRoute
  '/operator/result': typeof OperatorResultRoute
  '/operator/upload': typeof OperatorUploadRoute
  '/operator/uploads': typeof OperatorUploadsRoute
  '/verifier/dashboard': typeof VerifierDashboardRoute
  '/verifier/queue': typeof VerifierQueueRoute
  '/verifier/review': typeof VerifierReviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/queue': typeof AdminQueueRoute
  '/admin/users': typeof AdminUsersRoute
  '/operator/dashboard': typeof OperatorDashboardRoute
  '/operator/processing': typeof OperatorProcessingRoute
  '/operator/result': typeof OperatorResultRoute
  '/operator/upload': typeof OperatorUploadRoute
  '/operator/uploads': typeof OperatorUploadsRoute
  '/verifier/dashboard': typeof VerifierDashboardRoute
  '/verifier/queue': typeof VerifierQueueRoute
  '/verifier/review': typeof VerifierReviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/search'
    | '/admin/analytics'
    | '/admin/dashboard'
    | '/admin/queue'
    | '/admin/users'
    | '/operator/dashboard'
    | '/operator/processing'
    | '/operator/result'
    | '/operator/upload'
    | '/operator/uploads'
    | '/verifier/dashboard'
    | '/verifier/queue'
    | '/verifier/review'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/search'
    | '/admin/analytics'
    | '/admin/dashboard'
    | '/admin/queue'
    | '/admin/users'
    | '/operator/dashboard'
    | '/operator/processing'
    | '/operator/result'
    | '/operator/upload'
    | '/operator/uploads'
    | '/verifier/dashboard'
    | '/verifier/queue'
    | '/verifier/review'
  id:
    | '__root__'
    | '/'
    | '/search'
    | '/admin/analytics'
    | '/admin/dashboard'
    | '/admin/queue'
    | '/admin/users'
    | '/operator/dashboard'
    | '/operator/processing'
    | '/operator/result'
    | '/operator/upload'
    | '/operator/uploads'
    | '/verifier/dashboard'
    | '/verifier/queue'
    | '/verifier/review'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SearchRoute: typeof SearchRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminQueueRoute: typeof AdminQueueRoute
  AdminUsersRoute: typeof AdminUsersRoute
  OperatorDashboardRoute: typeof OperatorDashboardRoute
  OperatorProcessingRoute: typeof OperatorProcessingRoute
  OperatorResultRoute: typeof OperatorResultRoute
  OperatorUploadRoute: typeof OperatorUploadRoute
  OperatorUploadsRoute: typeof OperatorUploadsRoute
  VerifierDashboardRoute: typeof VerifierDashboardRoute
  VerifierQueueRoute: typeof VerifierQueueRoute
  VerifierReviewRoute: typeof VerifierReviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/queue': {
      id: '/admin/queue'
      path: '/admin/queue'
      fullPath: '/admin/queue'
      preLoaderRoute: typeof AdminQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operator/dashboard': {
      id: '/operator/dashboard'
      path: '/operator/dashboard'
      fullPath: '/operator/dashboard'
      preLoaderRoute: typeof OperatorDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operator/processing': {
      id: '/operator/processing'
      path: '/operator/processing'
      fullPath: '/operator/processing'
      preLoaderRoute: typeof OperatorProcessingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operator/result': {
      id: '/operator/result'
      path: '/operator/result'
      fullPath: '/operator/result'
      preLoaderRoute: typeof OperatorResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operator/upload': {
      id: '/operator/upload'
      path: '/operator/upload'
      fullPath: '/operator/upload'
      preLoaderRoute: typeof OperatorUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operator/uploads': {
      id: '/operator/uploads'
      path: '/operator/uploads'
      fullPath: '/operator/uploads'
      preLoaderRoute: typeof OperatorUploadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verifier/dashboard': {
      id: '/verifier/dashboard'
      path: '/verifier/dashboard'
      fullPath: '/verifier/dashboard'
      preLoaderRoute: typeof VerifierDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verifier/queue': {
      id: '/verifier/queue'
      path: '/verifier/queue'
      fullPath: '/verifier/queue'
      preLoaderRoute: typeof VerifierQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verifier/review': {
      id: '/verifier/review'
      path: '/verifier/review'
      fullPath: '/verifier/review'
      preLoaderRoute: typeof VerifierReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SearchRoute: SearchRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminQueueRoute: AdminQueueRoute,
  AdminUsersRoute: AdminUsersRoute,
  OperatorDashboardRoute: OperatorDashboardRoute,
  OperatorProcessingRoute: OperatorProcessingRoute,
  OperatorResultRoute: OperatorResultRoute,
  OperatorUploadRoute: OperatorUploadRoute,
  OperatorUploadsRoute: OperatorUploadsRoute,
  VerifierDashboardRoute: VerifierDashboardRoute,
  VerifierQueueRoute: VerifierQueueRoute,
  VerifierReviewRoute: VerifierReviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
